# Generated by Django 4.1.13 on 2024-01-22 21:27

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import s3_file_field.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_default_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTInputFile',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('file', s3_file_field.fields.S3FileField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('parameters', models.JSONField(blank=True, null=True)),
                (
                    'input_scan',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='sessions',
                        to='core.ctinputfile',
                    ),
                ),
                (
                    'owner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='sessions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='OutputImage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('file', models.FileField(upload_to='')),
                ('parameters', models.JSONField(blank=True, null=True)),
                (
                    'session',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='output_images',
                        to='core.session',
                    ),
                ),
            ],
        ),
    ]
