# Generated by Django 4.1.13 on 2024-01-31 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='parameters',
        ),
        migrations.CreateModel(
            name='InputParameters',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'carm_alpha',
                    models.IntegerField(
                        help_text='The desired alpha angulation of the C-arm in degrees.'
                    ),
                ),
                (
                    'carm_beta',
                    models.IntegerField(
                        help_text='The desired secondary angulation of the C-arm in degrees.'
                    ),
                ),
                (
                    'source_to_detector_distance',
                    models.FloatField(
                        help_text='The distance from the source to the detector in mm.'
                    ),
                ),
                (
                    'session',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='parameters',
                        to='core.session',
                    ),
                ),
            ],
        ),
    ]
