# Generated by Django 4.1.13 on 2024-02-04 00:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_remove_session_parameters_inputparameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.CharField(
                choices=[
                    ('not-started', 'Not Started'),
                    ('running', 'Running'),
                    ('processed', 'Processed'),
                ],
                default='not-started',
                max_length=32,
            ),
        ),
    ]
