# Generated by Django 4.1.13 on 2024-02-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0004_session_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputimage',
            name='file',
            field=models.FileField(upload_to='output_images'),
        ),
    ]
