# Generated by Django 4.1.13 on 2024-02-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0005_alter_outputimage_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outputimage',
            old_name='file',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='outputimage',
            name='image',
            field=models.ImageField(upload_to='output_images'),
        ),
    ]
