# Generated by Django 4.1.13 on 2024-02-13 18:51

from io import BytesIO
from pathlib import Path
from tempfile import TemporaryDirectory
from uuid import uuid4

from PIL import Image
from django.apps.registry import Apps
from django.core.files import File
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def add_thumbnails(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    OutputImage = apps.get_model('core', 'OutputImage')  # noqa: N806
    for output_image in OutputImage.objects.iterator():
        with TemporaryDirectory() as tmpdir:
            dest = Path(tmpdir) / 'image.png'
            img = Image.open(output_image.image)
            img.thumbnail((64, 64))
            img.save(dest)
            output_image.thumbnail = File(BytesIO(dest.read_bytes()), name=f'{uuid4()}.png')
            output_image.save()


def remove_thumbnails(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    OutputImage = apps.get_model('core', 'OutputImage')  # noqa: N806
    for output_image in OutputImage.objects.iterator():
        output_image.thumbnail.delete()
        output_image.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_outputimage_file_outputimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='outputimage',
            name='thumbnail',
            field=models.ImageField(upload_to='output_images/thumbnails', null=True),
        ),
        migrations.RunPython(code=add_thumbnails, reverse_code=remove_thumbnails),
        migrations.AlterField(
            model_name='outputimage',
            name='thumbnail',
            field=models.ImageField(upload_to='output_images/thumbnails', null=False),
        ),
    ]
