# Generated by Django 4.1.13 on 2024-02-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0007_outputimage_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputparameters',
            name='carm_alpha',
            field=models.IntegerField(
                blank=True,
                help_text='The desired alpha angulation of the C-arm in degrees.',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='inputparameters',
            name='carm_beta',
            field=models.IntegerField(
                blank=True,
                help_text='The desired secondary angulation of the C-arm in degrees.',
                null=True,
            ),
        ),
    ]
