# Generated by Django 4.1.13 on 2024-02-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0008_alter_inputparameters_carm_alpha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputparameters',
            name='carm_head_foot_translation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inputparameters',
            name='carm_push_pull',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inputparameters',
            name='carm_raise_lower',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
