# Generated by Django 4.1.13 on 2024-02-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_inputparameters_carm_head_foot_translation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outputimage',
            name='parameters',
        ),
        migrations.AddField(
            model_name='outputimage',
            name='carm_alpha',
            field=models.FloatField(
                blank=True,
                help_text='The desired alpha angulation of the C-arm in degrees.',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='outputimage',
            name='carm_beta',
            field=models.FloatField(
                blank=True,
                help_text='The desired secondary angulation of the C-arm in degrees.',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='outputimage',
            name='carm_head_foot_translation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outputimage',
            name='carm_push_pull',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outputimage',
            name='carm_raise_lower',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inputparameters',
            name='carm_alpha',
            field=models.FloatField(
                blank=True,
                help_text='The desired alpha angulation of the C-arm in degrees.',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='inputparameters',
            name='carm_beta',
            field=models.FloatField(
                blank=True,
                help_text='The desired secondary angulation of the C-arm in degrees.',
                null=True,
            ),
        ),
    ]
