# Generated by Django 4.1.13 on 2024-02-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_outputimage_parameters_outputimage_carm_alpha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='output_images_zip',
            field=models.FileField(blank=True, null=True, upload_to='output_images/zips'),
        ),
    ]
