# Generated by Django 4.1.13 on 2024-03-08 04:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_session_output_images_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputparameters',
            name='num_samples',
            field=models.PositiveIntegerField(
                default=100,
                help_text='The number of x-rays to generate with DeepDRR.',
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
