# Generated by Django 4.1.13 on 2024-03-08 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_inputparameters_num_samples'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputparameters',
            name='carm_alpha_kappa',
            field=models.FloatField(
                default=100,
                help_text='The desired kappa value to use in '
                'the von Mises distriubtion for C-arm alpha.',
            ),
        ),
        migrations.AddField(
            model_name='inputparameters',
            name='carm_beta_kappa',
            field=models.FloatField(
                default=100,
                help_text='The desired kappa value to use in '
                'the von Mises distriubtion for C-arm beta.',
            ),
        ),
    ]
