# Generated by Django 4.1.13 on 2024-03-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0013_inputparameters_carm_alpha_kappa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(
                choices=[
                    ('not-started', 'Not Started'),
                    ('running', 'Running'),
                    ('processed', 'Processed'),
                    ('cancelled', 'Cancelled'),
                ],
                default='not-started',
                max_length=32,
            ),
        ),
    ]
