# Generated by Django 4.1.13 on 2024-03-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_session_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputparameters',
            old_name='carm_push_pull',
            new_name='carm_push_pull_translation',
        ),
        migrations.RenameField(
            model_name='inputparameters',
            old_name='carm_raise_lower',
            new_name='carm_raise_lower_translation',
        ),
        migrations.AddField(
            model_name='inputparameters',
            name='carm_head_foot_std_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inputparameters',
            name='carm_push_pull_std_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inputparameters',
            name='carm_raise_lower_std_dev',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
