# Generated by Django 4.1.13 on 2024-03-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_carm_push_pull_inputparameters_carm_push_pull_translation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputparameters',
            name='detector_diameter',
            field=models.FloatField(default=1536, help_text='The detector diameter in mm.'),
        ),
    ]
