# Generated by Django 4.1.13 on 2024-04-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_session_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputparameters',
            name='detector_diameter',
            field=models.FloatField(default=228.6, help_text='The detector diameter in mm.'),
        ),
    ]
