# Generated by Django 5.0.4 on 2024-04-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_inputparameters_detector_diameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
