# Generated by Django 5.0.4 on 2024-04-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_session_celery_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputparameters',
            name='carm_alpha',
            field=models.FloatField(
                default=0, help_text='The desired alpha angulation of the C-arm in degrees.'
            ),
        ),
        migrations.AlterField(
            model_name='inputparameters',
            name='carm_alpha_kappa',
            field=models.FloatField(
                blank=True,
                help_text='The desired kappa value to use in the von Mises distriubtion'
                'for C-arm alpha.',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='inputparameters',
            name='carm_beta',
            field=models.FloatField(
                default=0, help_text='The desired secondary angulation of the C-arm in degrees.'
            ),
        ),
        migrations.AlterField(
            model_name='inputparameters',
            name='carm_beta_kappa',
            field=models.FloatField(
                blank=True,
                help_text='The desired kappa value to use in the von Mises distriubtion'
                'for C-arm beta.',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='inputparameters',
            name='carm_head_foot_translation',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='inputparameters',
            name='carm_push_pull_translation',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='inputparameters',
            name='carm_raise_lower_translation',
            field=models.FloatField(default=0),
        ),
    ]
