# Generated by Django 5.0.4 on 2024-04-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0020_alter_inputparameters_carm_alpha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputparameters',
            name='carm_alpha_kappa',
            field=models.FloatField(
                blank=True,
                help_text='The desired kappa value to use in the von Mises distriubtion '
                'for C-arm alpha.',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='inputparameters',
            name='carm_beta_kappa',
            field=models.FloatField(
                blank=True,
                help_text='The desired kappa value to use in the von Mises distriubtion '
                'for C-arm beta.',
                null=True,
            ),
        ),
    ]
