# Generated by Django 5.0.4 on 2024-10-16 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0021_alter_inputparameters_carm_alpha_kappa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleDataset',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('license', models.TextField()),
                ('source', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SampleDatasetFile',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('file', models.FileField(upload_to='sample_data')),
                (
                    'sample_dataset',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='files',
                        to='core.sampledataset',
                    ),
                ),
            ],
        ),
    ]
