# Generated by Django 5.0.4 on 2024-10-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_sampledataset_sampledatasetfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampledatasetfile',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sampledatasetfile',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
