# Generated by Django 5.1.2 on 2024-11-08 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_ctinputfile_created_inputparameters_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(
                choices=[
                    ('not-started', 'Not Started'),
                    ('queued', 'Queued'),
                    ('running', 'Running'),
                    ('processed', 'Processed'),
                    ('cancelled', 'Cancelled'),
                    ('deleting', 'Deleting'),
                ],
                default='not-started',
                max_length=32,
            ),
        ),
    ]
