# Generated by Django 5.1.2 on 2024-11-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0025_alter_session_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(
                choices=[
                    ('not-started', 'Not Started'),
                    ('queued', 'Queued'),
                    ('running', 'Running'),
                    ('processed', 'Processed'),
                    ('cancelled', 'Cancelling'),
                    ('deleting', 'Deleting'),
                ],
                default='not-started',
                max_length=32,
            ),
        ),
    ]
