# Generated by Django 5.1.2 on 2024-12-03 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_session_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sampledataset',
            old_name='source',
            new_name='source_name',
        ),
        migrations.AddField(
            model_name='sampledataset',
            name='source_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
