# Generated by Django 5.1.2 on 2024-12-03 01:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0027_rename_source_sampledataset_source_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='celery_task_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
