# Generated by Django 5.1.4 on 2025-01-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0029_contactformsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='started',
            field=models.DateTimeField(
                blank=True,
                help_text='When the session started processing (i.e. when it went into '
                'the QUEUED state)',
                null=True,
            ),
        ),
    ]
