# This action reboots the EC2 worker, which triggers a `git pull` and restarts the worker.
name: Reboot EC2 worker
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  reboot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::730335598236:role/GitHubActionsRole
          aws-region: us-east-1

      - name: Reboot the EC2 worker if it's currently running
        run: |
          instance_id=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=xray-genius-worker-0" --query "Reservations[*].Instances[*].InstanceId" --output text)
          instance_state=$(aws ec2 describe-instances --instance-ids $instance_id --query "Reservations[*].Instances[*].State.Name" --output text)
          if [ "$instance_state" == "running" ]; then
            aws ec2 reboot-instances --instance-ids $instance_id
          fi
